name: 03 - Workflow Runners

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OD
              run: |
                echo "This job is running on an Ubuntu runner."
                echo "Runner OS: $RUNNER_OS"
              