name: 05-2- filtersand activity types
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main    
        
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is running or synchronized and base branch is main"        